version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run test
      # upload and store test result into circleci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
